
export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'
export const SESSION_ENDED = 'SESSION_ENDED'
export const NO_INTERNET = 'NO_INTERNET'

export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT'
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const LOGIN_FAILED = 'LOGIN_FAILED'


export const REGISTER_ATTEMPT = 'REGISTER_ATTEMPT'
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL'
export const REGISTRATION_FAILED = 'REGISTER_FAILED'

export const POSTING_DATA = 'POSTING_DATA'
export const POSTING_SUCCESSFUL = 'POSTING_SUCCESSFUL'
export const POSTING_ERROR = 'POSTING_ERROR'

